### ISSUE TITLE
Dark modal shows light modal

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1241] opened 2021-08-03 01:21 UTC
The dark modal is defined under the class `.trumbowyg-dark` but is output in the code at the end of `<body>`.
Therefore the `.trumbowyg-dark .trumbowyg-modal-box` have no effect.

You could move the modal to underneath the `<div class="trumbowyg">` node instead. That would make the modal relative to the editor itself which might not be totally bad. Another solution is to set `.trumbowyg-dark` in the `<body>` tag.

I like the dark theme. But on a side note I would make it `.trumbowyg.trumbowyg-dark` instead of `.trumbowyg-dark .trumbowyg` and throw in a JS parameter `theme: 'dark'` that can trigger the theme.

**Comment by scscgit** [comment] 2021-08-15 11:27
I also have some issues with dark mode, specifically it seems to be related to the "reset-css" https://alex-d.github.io/Trumbowyg/documentation/#reset-css (which I'm using via vue-trumbowyg wrapper). When I add this CSS class manually, the dark mode disappears for the input:

![image](https://user-images.githubusercontent.com/3118390/129476571-7a0436a7-859f-49fa-b193-a03f1f7ef9e4.png)

---

But this seems to also occur even if I don't use this property in my project, in which case I suspect it to be caused by Vuetify's CSS normalization.

![image](https://user-images.githubusercontent.com/3118390/129476636-c82425fd-a5c5-463d-a49b-b58bd466bde4.png)

---

Also because the `trumbowyg-dark` class isn't supported by child elements (it must be on the div wrapper), there is no way to try to override this behavior manually. Is there any workaround possible if we use the CSS normalization? (And I'm also voting for adding `dark` as an option, or in general to make it a part of the "custom skin" https://alex-d.github.io/Trumbowyg/documentation/#custom-skin as an example of a use-case rather than a separate section documented only on a demo page.)

**Comment by Alex-D** [comment] 2022-11-14 16:03
Fixed in 2.26.0

**Closed by Alex-D** 2022-11-14 16:03 UTC
