### ISSUE TITLE
Cursor jumps to the left after typing formatted text

### ISSUE THREAD

**Issue by kkuchta** [Alex-D/Trumbowyg#95] opened 2015-03-05 04:12 UTC
This looks like a pretty nice wysiwyg editor, but the very first thing I tried (typing some bolded text) doesn't work.  :(

Steps:
1. Hit the 'Bold' button
2. Type "Foobar"
What actually comes out is "oobarF".

![weird_test](https://cloud.githubusercontent.com/assets/820965/6499110/b44319d2-c2aa-11e4-81af-37dd62cff777.gif)

This is from the demo on the front page of http://alex-d.github.io/Trumbowyg/.

**Comment by Alex-D** [comment] 2015-03-06 09:52
I need to look if this bug still present on the version 2 (master branch, in dev).

**Comment by Alex-D** [comment] 2015-03-12 00:40
Bug persist on v2 :(

**Comment by ra100** [comment] 2015-04-15 11:48
I think the problem is with t.semanticTag. I tried to comment those lines, and bold/italics works fine without jumping back. I know that that function has reason there, but at leas as temp workaround, those lines can be commented

//                t.semanticTag('b', 'strong');
//                t.semanticTag('i', 'em');

https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L844

**Comment by Alex-D** [comment] 2015-05-31 19:59
Fixed by PR #118 :D

**Closed by Alex-D** 2015-05-31 19:59 UTC
Labels: bug
