### ISSUE TITLE
Insert Caret at end of content?

### ISSUE THREAD

**Issue by MadMikeyB** [Alex-D/Trumbowyg#675] opened 2017-12-13 23:08 UTC
Hi,

On blur and focus / destroy - re-init, is there a way for the caret to be inserted at the end of the content rather than the beginning?

**Comment by Alex-D** [comment] 2017-12-14 12:31
Nope.

**Comment by Alex-D** [comment] 2017-12-14 12:31
Sort of duplicate of #629

**Closed by Alex-D** 2017-12-14 12:31 UTC

**Comment by MadMikeyB** [comment] 2017-12-14 19:00
Thanks :)

**Comment by mrmnmly** [comment] 2018-04-19 15:16
btw. is there any way of moving caret inside the editor via js?

**Comment by guirama** [comment] 2018-10-31 05:56
Hi,

What is the command to insert any HTML at caret .

Best Regards

**Comment by Alex-D** [comment] 2018-10-31 18:21
That's not OK in all browsers, but you can use execCmd with insertHtml:

https://github.com/Alex-D/Trumbowyg/blob/cf3c84cef53630f933bbd19e9db0b2372cfaf4bc/plugins/pasteembed/trumbowyg.pasteembed.js#L85
