### ISSUE TITLE
Switching between code and text view and back to code view loses &mdash; and &ndash;

### ISSUE THREAD

**Issue by wjhurley** [Alex-D/Trumbowyg#479] opened 2017-01-24 23:21 UTC
### Informations

**Browser + version**:Chrome Version 55.0.2883.87 m (64-bit)
**OS**: Windows 10
**Resolution**: 1920x1080

### How to reproduce the bug?

In code editor view, if you type in the the html escape codes &ndash; or &mdash; and then switch to text view, the proper characters are there, but if you switch back to code view, they are gone and replaced with basic dashes. I use this editor to create WordPress posts and even if I do not switch back to code view, the post is created without the escaped characters.

**Comment by Alex-D** [comment] 2017-01-25 10:31
Sorry but I can't resolve that. Seems to be a Chrome/other behaviour :(

**Comment by wjhurley** [comment] 2017-01-26 00:27
Well I just tested it in Firefox and Edge and it does the same thing, so it is not a Chrome issue.

**Comment by richardtallent** [comment] 2017-02-03 14:06
I believe this is a duplicate of #442, I've just discovered the same issue.

**Closed** 2017-02-03 21:57 UTC
Labels: duplicate, question, wontfix
