### ISSUE TITLE
Page reloads when adding links, images

### ISSUE THREAD

**Issue by mahabib** [Alex-D/Trumbowyg#958] opened 2019-04-16 11:53 UTC
### Description

Provide relevant details according to the context:
  - OS: Windows 10
  - Browser + version: Firefox Quantum 66.0.3 (64-bit)

### How to reproduce?
Add a new link or image in the editor it will reload the page.

@Alex-D When I am trying to a add link or an image it's generating a form and on confirm it's submitting it that is reloading the page.

**Comment by Alex-D** [comment] 2019-04-16 21:13
Can you provide a demo page which can helps me to reproduce the bug?

**Comment by Alex-D** [comment] 2019-04-16 21:15
It works on the demo page. So... I close this issue.

Feel free to provide me a demo page anyway. I think it's an issue due to JS on your side which override the Trumbowyg from listener.

**Closed by Alex-D** 2019-04-16 21:15 UTC
Labels: question

**Comment by mahabib** [comment] 2019-04-17 10:23
@Alex-D Thanks a lot.

The problem is happening when using older version jQuery, in my case it is jquery-2.2.4.

**Comment by Alex-D** [comment] 2019-04-17 19:36
Oh! Okay. Looks strange ^^' but OK.

Thanks for the feedback :)
