### ISSUE TITLE
First line should turn into a paragraph on enter.

### ISSUE THREAD

**Issue by niuage** [Alex-D/Trumbowyg#540] opened 2017-05-03 15:39 UTC
### Informations

**Browser + version**: Chrome 58.0
**OS**: OSX 10.10.2
**Tumbowyg version**: v2.5.1

### How to reproduce the bug?

Start typing in an editor. Press enter. Type some more. The first line is never turned into a paragraph.
Here's a gif of the issue as I'm seeing it: http://i.imgur.com/c3i1UwG.gif

Hopefully it's not the desired behavior. I did see this issue, and the owner says that the `<p>` tag should be added on enter, but it doesnt seem to be for me.

**Comment by niuage** [comment] 2017-05-05 16:36
Anybody else has this issue? Even before getting a fix if it is indeed an issue, I'd love to know it's not an issue on my end only.

**Comment by Alex-D** [comment] 2017-05-05 23:05
It seems to be a Trumbowyg issue but I don't have the time to fix it, sorry :/

**Comment by niuage** [comment] 2017-05-05 23:11
Can you give us hints maybe at how you'd go about fixing it?
Or can I switch tools programmatically and automatically choose Paragraph on page load?
Overall doesnt seem like it would be hard to fix for someone who knows his way around the code, but obviously I could be wrong.

**Comment by Alex-D** [comment] 2017-05-08 01:16
Try to switch semantic to false.

**Comment by niuage** [comment] 2017-05-08 15:13
Didn't work :(

**Comment by niuage** [comment] 2017-05-08 15:45
When you press Enter the first time, what triggers the "Paragraph mode"?

**Comment by Alex-D** [comment] 2017-05-09 09:10
The browser itself with contenteditable which is buggy... :(

**Comment by pancus** [comment] 2017-05-19 20:43
We ran into this issue too and can confirm it's a browser issue. The issue is up for being fixed in firefox 55 https://bugzilla.mozilla.org/show_bug.cgi?id=1297414

In the meantime we populate the blank form with "&lt;p&gt;&zwnj;&lt;/p&gt;" which seems to force FF to use <p> initially and then scrub it out afterwards.

**Comment by newterminator** [comment] 2017-05-20 22:16
Can confirm this issue also on:
Safari: 10.1 
Mac OS: 10.10.5

**Comment by niuage** [comment] 2017-05-23 18:18
I'm surprised that so many people are using this editor and not complaining about this issue. It's pretty huge. Couldn't trumbowyg itself initialize the content editable with with a paragraph or something?

**Comment by niuage** [comment] 2017-05-23 21:09
@pancus I've done what you suggested. It helps, but it doesnt remove the issue completely right?

If for instance you start by writing

```
first sentence

second sentence
```

Then if you move your cursor up to the middle of "first sentence" and press enter, it fails.

**Comment by pancus** [comment] 2017-05-23 22:51
@niuage oh it's not a fix, it's barely a workaround. But it does serve as a good demonstration of what the problem is.

**Comment by cyberwolfru** [comment] 2017-05-25 07:29
I have the same issue as OP, but there is no issue on this page: http://alex-d.github.io/Trumbowyg/ 
What is different there?

**Comment by kylebollinger** [comment] 2017-05-26 07:59
@pancus Ran into the same issue. Came up with this silly hack that seems to work for my implementation. Feel free to ignore this if you've moved on, just threw this together until a better fix is in place.

**Function to hack paragraph tags on empty Trumbo:**
```
function hackTrumbo() {
  var event = jQuery.Event('keydown');
  event.which = 13; // Enter
  $('#tEditor').focus().trigger(event);
  $('#tEditor').trumbowyg('empty');
  $('#tEditor').trumbowyg('html', "<p>Compose something epic</p>");
}
```

**If editor is empty, call the function after Trumbo has initialized:**
`$('#tEditor').trumbowyg().on('tbwinit', function(){ hackTrumbo() });`

**Comment by yprez** [comment] 2017-07-18 17:15
Possible duplicate of: #516

**Closed** 2017-07-18 17:18 UTC
Labels: bug:core, duplicate
