### ISSUE TITLE
Page crash/freeze/hang on Chomium-based browsers

### ISSUE THREAD

**Issue by stevenLT** [Alex-D/Trumbowyg#1259] opened 2021-10-26 14:32 UTC
Recently, many users told us that using the paragraph menu crashed their browser's tab. We noticed that the problem is also happening from the demo page. We have made many attempts and have had no problems with Mac OS. The problems seem to happen with Windows 10 whether it is on Edge or Chrome.

### Description

Relevant details according to the context:
  - Windows 10
  - Edge Lastest; Chrome Lastest
  - 1920 x 1080

### How to reproduce?

On Windows 10, Chrome Lastest (or other), on https://alex-d.github.io/Trumbowyg/
  - Select text
  - Click on Paragraph menu
  - Select Header 1 for example

You may need to do many attempts to see the bug happen. No console error.

**Comment by Alex-D** [comment] 2021-10-30 18:10
I can't reproduce the bug on Chrome, but I can on Edge. That's really strange.

**Comment by pobretv** [comment] 2021-10-30 21:57
I use chromium based browser ( Brave ) on MacOS with M1 chip and I can confirm that the page crashes

**Comment by MWelkerH** [comment] 2021-11-01 08:06
as @kiewietr wrote, its probably the xlink:href problem, see (https://css-tricks.com/on-xlinkhref-being-deprecated-in-svg/). Maybe replacing <use xlink:href ... /> by <use href ... /> could solve the problem.

**Comment by messalas** [comment] 2021-11-01 08:42
I have the same issue, i hope it will be fixed soon

**Comment by MWelkerH** [comment] 2021-11-01 08:42
Replacing <use xlink:href ... /> by <use href ... /> seems not to solve the problem.

**Comment by IvanDreamer** [comment] 2021-11-01 10:15
I can confirm same behaviour on Chrome, but not on Firefox and Safari. 
When I click any dropdown the page is freezing and crashing. 
What would be the fix for it?

**Comment by Alex-D** [comment] 2021-11-01 10:25
Maybe try this for now:

```css
.trumbowyg-dropdown button svg {
    display: none;
}
```

**Comment by messalas** [comment] 2021-11-01 10:38
On initialization  `$('.html-editor').trumbowyg({...});`, I deleted the option ['formatting'] and it works also, till a solution is found.

**Comment by IvanDreamer** [comment] 2021-11-01 10:43
> Maybe try this for now:
> 
> ```css
> .trumbowyg-dropdown button svg {
>     display: none;
> }
> ```

Thank you! It works .)

**Comment by chaffeqa** [comment] 2021-11-04 18:23
This is happening on OSX Chrome as well. 

I can reproduce every time by typing text, then highlighing a word, and clicking the "Insert Link" dropdown.  After hovering over the first option, the page hangs forever

**Comment by rainerborene** [comment] 2021-11-04 18:30
I could reproduce it on Browserstack using Windows 10 and Chrome 96.0.4664.18 (Official Build) (64-bit).

**Comment by TFleury** [comment] 2021-11-08 16:42
Chromium bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1262589)
It seems to have been fixed today, but I don't know when it will be available in our browsers.

**Comment by Alex-D** [comment] 2022-08-17 08:47
No feedback since a more than a year, I think I can tell that this is fixed :)

**Closed by Alex-D** 2022-08-17 08:47 UTC
Labels: bug:core
