### ISSUE TITLE
Upload plugin

### ISSUE THREAD

**Issue by Matoo125** [Alex-D/Trumbowyg#531] opened 2017-04-11 08:34 UTC
Hello. First of all, very good job with this project. 👍 

I'm trying to make use of upload plugin. For some reason it does not work in my case. The problem is I am not getting any response so have no idea what went wrong. If I use default options I am not even getting an 'error' message. If I use imgur as in your example it works. I get 'error' only if I do not echo anything from serverPath.

I believe this upload plugin is very important and deserves some documentation.

**Comment by thealexander90** [comment] 2017-04-24 13:57
Hi, I just used it and managed to make it work.

First you need to manually copy the file using `$_FILES` global and after you processed it you need to output a json response like `echo json_encode($data)` where `$data` is an array with a `success` variable and another variable called `file` with the path to the file.

If you want you can use different names but you need to change these values in the js of the plugin.
( you can find them in the `defaultOptions` ).

Hope this helps you :)

**Comment by Alex-D** [comment] 2017-09-13 22:50
Duplicate of #205

**Closed by Alex-D** 2017-09-13 22:50 UTC
Labels: documentation, duplicate, plugin
