### ISSUE TITLE
First type on Firefox

### ISSUE THREAD

**Issue by kalerosky** [Alex-D/Trumbowyg#496] opened 2017-02-17 11:02 UTC
On Firefox when the box is empty and you're going to write for first time, every key you push is put in a new \<p\>.
In Chrome and Edge works fine.

### Informations

**Browser + version**: Firefox 51.0.1
**OS**: Windows 7/8/10 
**Resolution**: 1280x1024

### How to reproduce the bug?
Simply open this html with Firefox:

```html
<!DOCTYPE html\>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>    
    <link rel="Stylesheet" href="Styles/trumbowyg.min.css"/>
    <script type="text/javascript" src="Scripts/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="Scripts/trumbowyg.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () { $("#ChipAhoi").trumbowyg({}); });
    </script>
</head>
<body>
    <form id="form1">
        <div>
            <textarea id="ChipAhoi"></textarea>
        </div>
    </form>
</body>
</html>
```

**Comment by martoriro** [comment] 2017-02-17 21:49
@Alex-D 
Hi Alex, i know it's just been reported but do you have any update about when it could be fixed?
Thanks !

**Comment by martoriro** [comment] 2017-02-17 21:58
Just discovered that disabling semantic tags seems to fix the issue

**Comment by Alex-D** [comment] 2017-02-18 00:16
Yep, it's due to semantic wrap in p

**Comment by teamayu** [comment] 2017-02-20 06:26
If you disable the semantics you get two sets of tags similar on the toolbar.

![20-02-2017-142420](https://cloud.githubusercontent.com/assets/10624092/23114182/78824440-f778-11e6-96bb-6fd7d068522b.png)

**Comment by Alex-D** [comment] 2017-02-20 09:59
Juste need to change this from `4` to `3`
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L425

**Comment by teamayu** [comment] 2017-02-20 10:11
Thank you Alex. Great plugin btw.

**Comment by istrau2** [comment] 2017-04-06 16:10
+1, my users are complaining about this.

**Comment by yprez** [comment] 2017-07-18 17:23
Looks like a duplicate of 502 which was fixed

**Comment by teamayu** [comment] 2017-08-16 21:57
Semantics issue not fixed in 2.7.0

**Comment by Alex-D** [comment] 2017-12-02 21:38
Seems to be a Firefox bug since I already call: 

```javascript
t.doc.execCommand('defaultParagraphSeparator', false, 'p');
```

**Closed by Alex-D** 2017-12-02 21:38 UTC
Labels: bug:core
