### ISSUE TITLE
Delete very letters using backspace [CHROME]

### ISSUE THREAD

**Issue by ThibDums** [Alex-D/Trumbowyg#918] opened 2019-01-24 13:22 UTC
### Informations

**Browser version**:  Version 71.0.3578.98 (Build officiel) (64 bits)
**OS**: Windows 10
**Screen resolution**: Every resolutions

### How to reproduce the bug?
On certain textarea, when i write the first line and want to undo some characters, the whole line is erased.
But if i put a space at the first character or if i go to next line to write, everything is ok ....
How can i solve it ? (Actually i add a &nbsp; char on the focus of my textarea if it is empty...)

**Comment by Alex-D** [comment] 2019-01-24 14:00
Hey!

Since I cannot reproduce the bug, I close this issues and will reopen if you make me a jsbin/codepen/whatever which helps me to reproduce the bug.

**Closed by Alex-D** 2019-01-24 14:00 UTC
