### ISSUE TITLE
Cleanup HTML

### ISSUE THREAD

**Issue by Xethron** [Alex-D/Trumbowyg#103] opened 2015-03-27 12:53 UTC
Playing a bit with the markup, I managed to change:
```html
<p>This is nice man</p>
```
into
```html
<p style="text-align: left;">
    This is&nbsp;
    <span style="line-height: 25.2000007629395px;">ni</span>
    <span style="line-height: 25.2000007629395px;">ce</span>
    <span style="line-height: 25.2000007629395px;">&nbsp;</span>
    <span style="line-height: 25.2000007629395px;">man</span>
</p>
```

This needs to be cleaned up again to `<p>This is nice man</p>`

**Comment by bytestream** [comment] 2015-04-28 16:35
@Xethron can you provide some details on how to replicate this?

**Comment by grammophone** [comment] 2015-07-16 09:08
Use Chrome (mine is Version 43.0.2357.134 m) and play with numbered or unnumbered lists to reproduce it righ away. Doesn't happen with Explorer.

**Comment by feydk** [comment] 2015-08-19 13:00
Confirmed. In Chrome, unordered lists get all sorts of inline styles, including line-height and font-family.

**Comment by Alex-D** [comment] 2016-02-07 17:34
Seems like fixed in Chrome. I can't reproduce this bug now.

**Closed** 2016-02-07 17:38 UTC
Labels: duplicate, enhancement
