### ISSUE TITLE
Add an option for inserting smiley markup

### ISSUE THREAD

**Issue by AttitudeMonger** [Alex-D/Trumbowyg#323] opened 2016-07-10 04:32 UTC
I want to give an additional button for inserting smileys. When user clicks the button, a popup is shown nearby displaying some 30 smiley icons, clicking any of which inserts that into the caret position.

How do I add this button and the functionality here?

**Comment by Alex-D** [comment] 2016-07-11 09:54
Idk. Maybe on the color plugin base, changing colors squares by smileys and by calling `insertImage` with the smiley URL.

**Comment by graphek** [comment] 2016-08-02 10:46
any progress on this? i'm interested as well!

**Comment by AttitudeMonger** [comment] 2016-08-02 11:22
Not sure right now. I am planning to do it like Facebook, let the users use markup like :) or :( in the text, then at the time of getting the HTML and pasting ti back, parse through such markups, convert them to respective inline images and render alongwith the rest of the content.

**Comment by graphek** [comment] 2016-08-02 11:42
Sounds good! I'm currently looking in a implemenation with at.js

**Comment by NicolasPion** [comment] 2016-08-03 13:21
Hi,
I do this (based on colors plugin + trumbowyg.execCmd('insertText' ....), but i dont know if i can do a pull-request because it depends on [emojifyjs](https://github.com/Ranks/emojify.js) :

![screenflow](https://cloud.githubusercontent.com/assets/11868633/17366836/8b4e5fac-598d-11e6-94b0-ee598e0a7a97.gif)

**Comment by graphek** [comment] 2016-08-03 16:40
@NicolasPion 
wow, thats an awesome implementation! It would be really great, if you could share the code somehow :) I think that would be a great enhancement for the trumbowyg editor, emojis is the only thing i missed on the editor.

best regards

**Comment by NicolasPion** [comment] 2016-08-03 18:32
@graphek, thanks !
PR & files : https://github.com/Alex-D/Trumbowyg/pull/354
;-)

**Comment by Alex-D** [comment] 2016-08-03 18:40
You can PR them in two plugins :)

**Comment by muyiwaoyeniyi** [comment] 2016-12-16 14:25
@NicolasPion There is an issue with the scroll bar in the emoji dropdown.

Testing in:
Chrome 54.0.2840 and Latest Firefox
Ubuntu 16.04

Using version 2.3.0 but I replicated this issue in 2.4.2

You can't click on the emoji scroll bar. When you do so, the emoji dropdown goes away. I believe this is happening because the dropdown as a whole has a close on click event attached to it. But that affects the scroll bar. The emojis themselves probably need a container separate from the dropdown container.

I tried to track down where this is done in you code but I couldn't. If you point me in the right direction, maybe I can fix it. Thanks.

Thanks.

**Comment by NicolasPion** [comment] 2016-12-16 17:53
Hi @muyiwaoyeniyi , I think it's not emoji plugin related (you can reproduce this issue with the "color" plugins for exemple, if you dont click on a color icon but you click inside the dropdown.. in a "white" area)

I think this PR can resolv that 😈  : https://github.com/Alex-D/Trumbowyg/pull/459

**Comment by muyiwaoyeniyi** [comment] 2016-12-16 18:34
@NicolasPion Thanks for the response and PR.. Yea I didnt try out the color plugin. But good to know.

All the best.

**Comment by Alex-D** [comment] 2016-12-17 22:22
Merged :)

**Closed** 2016-12-17 22:22 UTC
Labels: need contributor, plugin

**Comment by danman1234** [comment] 2017-05-17 19:10
Helo, i have done the emojifyjs : plugin, i get smileys, with text, but how to get the images inside the div??

**Comment by NicolasPion** [comment] 2017-05-17 19:29
@danman1234, you can add something like : 

```
function handleEmoji()
{
	emojify.setConfig({
		img_dir : '/vendor/emojify.js/dist/images/basic',
	});
	emojify.run();  
}

$('.trumbowyg-editor').bind('input propertychange', function() {
	handleEmoji();
});
```

**Comment by danman1234** [comment] 2017-05-18 08:44
This works, but as before too sometimes it shows the smiley ico and othertimes not. 
It looks a bit hacky.

If i refeesh 4 times, then the smiley ico will show up.
Also i want to remove tons of smileys, i just need 10 for faster laoding, but in trumpowyg.emoji.js i have removed a lot from the:

    var defaultOptions = {
        emojiList: 

but then it never shows up anymore.

**Comment by NicolasPion** [comment] 2017-05-18 08:59
@danman1234 try this PR (not yet merged) : https://github.com/Alex-D/Trumbowyg/pull/548
With this PR, you can specify an array of icons (ex here: https://github.com/Alex-D/Trumbowyg/issues/547), and you dont need anymore emojify.js

**Comment by Ydalb** [comment] 2017-07-04 10:01
hey @graphek : possible to share your at.js implementation please ? :)

**Comment by graphek** [comment] 2017-07-04 11:05
@Ydalb Sorry, i dont have the code for the smilies anymore because i liked the toolbar-version more. But i still use At.js for @mentions like this:

`        // @MENTIONS

        $(selector).atwho({
          at: "@",
          data: this.api+'users/getForMentions',
          displayTpl: '<li class="mentionLi"><img src="'+this.cdn+'/avatare/${avatar}" alt="${name}" /> ${name} </li>',
          insertTpl: '<span class="mention" value="${slug}">${name}</span>',
        });`

best regards

**Comment by Ydalb** [comment] 2017-07-04 11:13
Nevermind @graphek , I also implemented the toolbar-version :D

But I also use at.js for mentions, love it ❤️

**Comment by mavinalim** [comment] 2018-04-10 03:13
@Ydalb @graphek Sorry to open up this post. How did you guys integrate @mention? I was able to use At.js to integreat into regular textarea but I am unable to make it with with Trumbowyg editor. It only works if i switch the editor into source code mode where you can see "<b>text</b>. Thanks :)
